In [2]:
import pandas as pd
import numpy as np
import os

In [3]:
df1 = pd.read_csv("../../Dataset/games_detailed_info.csv")
df1

C:\Users\COMPUTER\AppData\Local\Temp\ipykernel_18516\436831389.py:1: DtypeWarning: Columns (29,48) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv("../../Dataset/games_detailed_info.csv")

,Unnamed: 0,type,id,thumbnail,image,primary,alternate,description,yearpublished,minplayers,...,War Game Rank,Customizable Rank,Children's Game Rank,RPG Item Rank,Accessory Rank,Video Game Rank,Amiga Rank,Commodore 64 Rank,Arcade Rank,Atari ST Rank
0,0,boardgame,30549,https://cf.geekdo-images.com/S3ybV1LAp-8SnHIXL...,https://cf.geekdo-images.com/S3ybV1LAp-8SnHIXL...,Pandemic,"['EPIZOotic', 'Pandemia', 'Pandemia 10 Anivers...","In Pandemic, several virulent diseases have br...",2008,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,boardgame,822,https://cf.geekdo-images.com/okM0dq_bEXnbyQTOv...,https://cf.geekdo-images.com/okM0dq_bEXnbyQTOv...,Carcassonne,"['Carcassonne Jubilee Edition', 'Carcassonne: ...",Carcassonne is a tile-placement game in which ...,2000,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,boardgame,13,https://cf.geekdo-images.com/W3Bsga_uLP9kO91gZ...,https://cf.geekdo-images.com/W3Bsga_uLP9kO91gZ...,Catan,"['CATAN', 'Catan (Колонизаторы)', 'Catan telep...","In CATAN (formerly The Settlers of Catan), pla...",1995,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,boardgame,68448,https://cf.geekdo-images.com/RvFVTEpnbb4NM7k0I...,https://cf.geekdo-images.com/RvFVTEpnbb4NM7k0I...,7 Wonders,"['7 csoda', '7 Cudów Świata', '7 divů světa', ...",You are the leader of one of the 7 great citie...,2010,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,boardgame,36218,https://cf.geekdo-images.com/j6iQpZ4XkemZP07HN...,https://cf.geekdo-images.com/j6iQpZ4XkemZP07HN...,Dominion,"['Dominion: Basisspiel', 'Dominion: In naam va...","&quot;You are a monarch, like your parents bef...",2008,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21626,21626,boardgame,296892,https://cf.geekdo-images.com/d37HVSmlYM2ZQpaKD...,https://cf.geekdo-images.com/d37HVSmlYM2ZQpaKD...,Sacred Rites,NaN,It has come time to honor the traditions of th...,2020,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21627,21627,boardgame,217378,https://cf.geekdo-images.com/BDS9Ndm2gb8QyE-i1...,https://cf.geekdo-images.com/BDS9Ndm2gb8QyE-i1...,BABEL,NaN,BABEL is a balancing game in which players mak...,2016,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21628,21628,boardgame,18063,https://cf.geekdo-images.com/NRIjTeX6AbdhOp-w1...,https://cf.geekdo-images.com/NRIjTeX6AbdhOp-w1...,Goldrush,"['Arizona', 'Guldfeber', 'Kultakuume']",From the rules:&#10;&#10;Players are prospecto...,1970,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21629,21629,boardgame,10052,https://cf.geekdo-images.com/EGOJ027F8r3Nln1r0...,https://cf.geekdo-images.com/EGOJ027F8r3Nln1r0...,Bongo Kongo,NaN,Each player takes a position adjacent to one o...,1989,2,...,NaN,NaN,350,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21630,21630,boardgame,165946,https://cf.geekdo-images.com/UQYTdmJHe_s_EiIIu...,https://cf.geekdo-images.com/UQYTdmJHe_s_EiIIu...,Green Beret: Vietnam,['Green Berets: Vietnam'],Green Beret: Vietnam gives you command of a Gr...,2015,1,...,2275.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
colss = ['id', 'primary', 'image']
bg_df = df1[colss].rename(columns={"id" : "boardgame_id" , "primary" : "boardgame_name"})
bg_df

,boardgame_id,boardgame_name,image
0,30549,Pandemic,https://cf.geekdo-images.com/S3ybV1LAp-8SnHIXL...
1,822,Carcassonne,https://cf.geekdo-images.com/okM0dq_bEXnbyQTOv...
2,13,Catan,https://cf.geekdo-images.com/W3Bsga_uLP9kO91gZ...
3,68448,7 Wonders,https://cf.geekdo-images.com/RvFVTEpnbb4NM7k0I...
4,36218,Dominion,https://cf.geekdo-images.com/j6iQpZ4XkemZP07HN...
...,...,...,...
21626,296892,Sacred Rites,https://cf.geekdo-images.com/d37HVSmlYM2ZQpaKD...
21627,217378,BABEL,https://cf.geekdo-images.com/BDS9Ndm2gb8QyE-i1...
21628,18063,Goldrush,https://cf.geekdo-images.com/NRIjTeX6AbdhOp-w1...
21629,10052,Bongo Kongo,https://cf.geekdo-images.com/EGOJ027F8r3Nln1r0...
21630,165946,Green Beret: Vietnam,https://cf.geekdo-images.com/UQYTdmJHe_s_EiIIu...

### Test - check result what is the average column in bg_df?
==> It is rating for each boardgame.

In [5]:

ratings = pd.read_csv("../Datasets/ratings.csv")

In [6]:
ratings

,user_name,rating,comment,boardgame_id,boardgame_name
0,Staxston,9.2,Only game I really play solo.,171835,Posthuman
1,Sheylon,3.0,Cute pieces but this isn't much of a game. Rol...,5824,The Kids of Catan
2,jens_hoppe,3.0,Initial impression. Takes heavy-weight German-...,25554,Notre Dame
3,bcnevan,5.0,Shores of Tripoli succeeds in some ways. It is...,237860,The Shores of Tripoli
4,ruelgaviola,8.0,Donated,17329,Animal Upon Animal
...,...,...,...,...,...
673718,Andy Parsons,5.0,I found the theme of Say Bye... quite appealin...,140795,Say Bye to the Villains
673719,PHIL4477,4.0,Another trivia game. I bought it because the b...,32441,Bezzerwizzer
673720,EmeraldYam,7.0,(As of [b]3[/b] plays) Quite original card-bas...,125315,FlowerFall
673721,PaleHorseRider,6.0,Good version of Apples to Apples. It has cons...,104234,Sour Apples to Apples
673722,Sigisgrim,8.0,Far better than traditional Risk.,4324,Risk: The Lord of the Rings

In [7]:
test = ratings.groupby(["boardgame_id", "boardgame_name"])["rating"].count()

In [8]:
df_test = pd.DataFrame(test)
df_test = df_test.reset_index()
# df_test[df_test['name'] == "Pandemic"]
df_test = df_test.rename(columns= {"rating" : "rating_counts"})
df_test

       boardgame_id                       boardgame_name  rating_counts
0                 1                           Die Macher            293
1                 2                         Dragonmaster             44
2                 3                              Samurai            621
3                 4                       Tal der Könige             23
4                 5                              Acquire            948
...             ...                                  ...            ...
20771        348955  Rock Paper Scissors: Deluxe Edition              3
20772        349131                             Splitter              2
20773        349805                   Bismarck Solitaire              3
20774        350736                              Voyages             14
20775        350992                          Neuroriders              6

[20776 rows x 3 columns]

In [9]:
test1 = ratings.groupby(["boardgame_id", "boardgame_name"])["rating"].mean()
df_test_1 = pd.DataFrame(test1)
df_test_1 = df_test_1.reset_index()
# df_test_1[df_test_1['name'] == "Pandemic"]
df_test_1 = df_test_1.rename(columns= {"rating" : "rating_averages"})
df_test_1

       boardgame_id                       boardgame_name  rating_averages
0                 1                           Die Macher         7.643515
1                 2                         Dragonmaster         6.568182
2                 3                              Samurai         7.560837
3                 4                       Tal der Könige         6.576087
4                 5                              Acquire         7.418565
...             ...                                  ...              ...
20771        348955  Rock Paper Scissors: Deluxe Edition         3.666667
20772        349131                             Splitter         5.250000
20773        349805                   Bismarck Solitaire         7.333333
20774        350736                              Voyages         8.557143
20775        350992                          Neuroriders         7.916667

[20776 rows x 3 columns]

In [10]:
df_test_all = df_test.merge(df_test_1, on=["boardgame_id","boardgame_name"])
df_test_all

,boardgame_id,boardgame_name,rating_counts,rating_averages
0,1,Die Macher,293,7.643515
1,2,Dragonmaster,44,6.568182
2,3,Samurai,621,7.560837
3,4,Tal der Könige,23,6.576087
4,5,Acquire,948,7.418565
...,...,...,...,...
20771,348955,Rock Paper Scissors: Deluxe Edition,3,3.666667
20772,349131,Splitter,2,5.250000
20773,349805,Bismarck Solitaire,3,7.333333
20774,350736,Voyages,14,8.557143
20775,350992,Neuroriders,6,7.916667

In [11]:
main_df = df_test_all.merge(bg_df, on=["boardgame_id","boardgame_name"], how="left") # do image có một số boardgame không có ảnh nên nếu gộp lại thì nó bỏ đi các null, vì vậy how= "left để loại bỏ trường hợpp này"
main_df

,boardgame_id,boardgame_name,rating_counts,rating_averages,image
0,1,Die Macher,293,7.643515,https://cf.geekdo-images.com/rpwCZAjYLD940NWwP...
1,2,Dragonmaster,44,6.568182,https://cf.geekdo-images.com/oQYhaJx5Lg3KcGis2...
2,3,Samurai,621,7.560837,https://cf.geekdo-images.com/o9-sNXmFS_TLAb7Zl...
3,4,Tal der Könige,23,6.576087,https://cf.geekdo-images.com/nYiYhUlatT2DpyXaJ...
4,5,Acquire,948,7.418565,https://cf.geekdo-images.com/3C--kJRhi6kTPHsr9...
...,...,...,...,...,...
20771,348955,Rock Paper Scissors: Deluxe Edition,3,3.666667,https://cf.geekdo-images.com/TRCPgnDKCu8civrbB...
20772,349131,Splitter,2,5.250000,https://cf.geekdo-images.com/6ILh7aNVHosY-m5gG...
20773,349805,Bismarck Solitaire,3,7.333333,https://cf.geekdo-images.com/NscesBNKqS_6h0sgN...
20774,350736,Voyages,14,8.557143,https://cf.geekdo-images.com/TkC7AIQD2jud20dCc...
20775,350992,Neuroriders,6,7.916667,https://cf.geekdo-images.com/u-U-nP11CYSnO2riF...

In [12]:
main_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20776 entries, 0 to 20775
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   boardgame_id     20776 non-null  int64
 1   boardgame_name   20776 non-null  object
 2   rating_counts    20776 non-null  int64
 3   rating_averages  20776 non-null  float64
 4   image            20564 non-null  object
dtypes: float64(1), int64(2), object(2)
memory usage: 811.7+ KB

#### Calculate weighted ratings serve as check weight for contributor.

In [38]:
# x = 0
# for i in (main_df["rating_counts"]>1550).astype(int).tolist():
#     if i == 1:
#         x += 1
# print(x)

19

In [13]:
# Calculate all the components 
number_of_ratings = main_df["rating_counts"]
ratings = main_df["rating_averages"]
ratings_average = main_df["rating_averages"].mean()
minimum_list = main_df["rating_counts"].quantile(0.75)
print(f" Number of ratings for each boardgame: {number_of_ratings}")
print(f" Ratings for each boardgame: {ratings}")
print(f" Ratings Average for each boardgame: {ratings_average}")
print(f" The Minimum range for all of boardgame: {minimum_list}")

 Number of ratings for each boardgame: 0        293
1         44
2        621
3         23
4        948
        ...
20771      3
20772      2
20773      3
20774     14
20775      6
Name: rating_counts, Length: 20776, dtype: int64
 Ratings for each boardgame: 0        7.643515
1        6.568182
2        7.560837
3        6.576087
4        7.418565
           ...
20771    3.666667
20772    5.250000
20773    7.333333
20774    8.557143
20775    7.916667
Name: rating_averages, Length: 20776, dtype: float64
 Ratings Average for each boardgame: 6.383654138085428
 The Minimum range for all of boardgame: 19.0

In [71]:
# Calculate all the components 
main_df["weight_ratings"] = ((ratings*number_of_ratings) + (ratings_average * minimum_list)) / (number_of_ratings + minimum_list)
main_df

,boardgame_id,boardgame_name,rating_counts,rating_averages,image,weight_ratings
0,1,Die Macher,293,7.643515,https://cf.geekdo-images.com/rpwCZAjYLD940NWwP...,7.566793
1,2,Dragonmaster,44,6.568182,https://cf.geekdo-images.com/oQYhaJx5Lg3KcGis2...,6.512531
2,3,Samurai,621,7.560837,https://cf.geekdo-images.com/o9-sNXmFS_TLAb7Zl...,7.525890
3,4,Tal der Könige,23,6.576087,https://cf.geekdo-images.com/nYiYhUlatT2DpyXaJ...,6.489034
4,5,Acquire,948,7.418565,https://cf.geekdo-images.com/3C--kJRhi6kTPHsr9...,7.398231
...,...,...,...,...,...,...
20771,348955,Rock Paper Scissors: Deluxe Edition,3,3.666667,https://cf.geekdo-images.com/TRCPgnDKCu8civrbB...,6.013156
20772,349131,Splitter,2,5.250000,https://cf.geekdo-images.com/6ILh7aNVHosY-m5gG...,6.275687
20773,349805,Bismarck Solitaire,3,7.333333,https://cf.geekdo-images.com/NscesBNKqS_6h0sgN...,6.513156
20774,350736,Voyages,14,8.557143,https://cf.geekdo-images.com/TkC7AIQD2jud20dCc...,7.305740
20775,350992,Neuroriders,6,7.916667,https://cf.geekdo-images.com/u-U-nP11CYSnO2riF...,6.751577

In [73]:
main_df = main_df.sort_values(by= ["weight_ratings"], ascending=False)
main_df

,boardgame_id,boardgame_name,rating_counts,rating_averages,image,weight_ratings
10800,115746,War of the Ring: Second Edition,427,8.771897,https://cf.geekdo-images.com/ImPgGag98W6gpV1KV...,8.670156
16465,224517,Brass: Birmingham,570,8.695292,https://cf.geekdo-images.com/x3zxjr-Vw5iU4yDPg...,8.620723
16273,220308,Gaia Project,406,8.637998,https://cf.geekdo-images.com/hGWFm3hbMlCDsfCsa...,8.537215
17612,246900,Eclipse: Second Dawn for the Galaxy,142,8.756901,https://cf.geekdo-images.com/Oh3kHw6lweg6ru71Q...,8.476829
13864,174430,Gloomhaven,1405,8.499074,https://cf.geekdo-images.com/sZYp_3BTDGjh2unaZ...,8.470849
...,...,...,...,...,...,...
18963,276022,Alien: USCSS Nostromo,28,1.321429,https://cf.geekdo-images.com/b7cH4UQM7PFraumDd...,3.367860
5236,11901,Tic-Tac-Toe,206,2.937816,https://cf.geekdo-images.com/UImMYmMZKE4AGTMPH...,3.228797
3240,5432,Chutes and Ladders,217,2.922281,https://cf.geekdo-images.com/P1qJDS_DFTtP_FrpW...,3.200951
3948,7316,Bingo,113,2.523894,https://cf.geekdo-images.com/7xqN6StcQz1FoGplo...,3.079465
5943,16398,War,113,2.369912,https://cf.geekdo-images.com/CeBpBleLUkV6uM-98...,2.947647

In [74]:
main_df.to_csv("../Datasets/weight_hybdrid_RS_dataset.csv")