In [1]:
import pandas as pd
import numpy as np
import pickle 
import os

In [2]:
data = pd.read_csv("../Datasets/cfb_dataset.csv")
data

,user_name,rating,boardgame_id,boardgame_name,rating_count,rating_mean
0,jens_hoppe,3.0,25554,Notre Dame,192,7.111125
1,KrisVerbeeck,7.0,25554,Notre Dame,192,7.111125
2,bazik123,6.0,25554,Notre Dame,192,7.111125
3,Chris Coyote,6.5,25554,Notre Dame,192,7.111125
4,Orph,7.0,25554,Notre Dame,192,7.111125
...,...,...,...,...,...,...
127117,Michiel,4.5,95,Igel Ärgern,31,6.041935
127118,dturnerfish,6.5,95,Igel Ärgern,31,6.041935
127119,jayjonbeach,3.0,95,Igel Ärgern,31,6.041935
127120,Defdamesdompi,6.5,95,Igel Ärgern,31,6.041935
127121,Scoopex,8.0,95,Igel Ärgern,31,6.041935

In [3]:
### Cleaned Dataset
data.drop_duplicates(["boardgame_id", "user_name"], inplace= True)
data

,user_name,rating,boardgame_id,boardgame_name,rating_count,rating_mean
0,jens_hoppe,3.0,25554,Notre Dame,192,7.111125
1,KrisVerbeeck,7.0,25554,Notre Dame,192,7.111125
2,bazik123,6.0,25554,Notre Dame,192,7.111125
3,Chris Coyote,6.5,25554,Notre Dame,192,7.111125
4,Orph,7.0,25554,Notre Dame,192,7.111125
...,...,...,...,...,...,...
127117,Michiel,4.5,95,Igel Ärgern,31,6.041935
127118,dturnerfish,6.5,95,Igel Ärgern,31,6.041935
127119,jayjonbeach,3.0,95,Igel Ärgern,31,6.041935
127120,Defdamesdompi,6.5,95,Igel Ärgern,31,6.041935
127121,Scoopex,8.0,95,Igel Ärgern,31,6.041935

In [4]:
## Create Matrix for the User_Boardgame Interaction using pivot function
bg_pivot = data.pivot_table(columns="user_name", index="boardgame_name", values="rating")
bg_pivot

user_name,1 Family Meeple,1000rpm,100pcBlade,1point21gigawatts,2ndPlace,3dicebombers,4Corners,521tiger,5th Beatles,ALGO,...,zaubererer,zautman,zb1035,zedeemia,zefquaavius,zeotter,zgabor,zombiegod,zumba,zumikon
boardgame_name,,,,,,,,,,,,,,,,,,,,,
10 Days in Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10 Days in Asia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10 Days in Europe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10 Days in the USA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11 nimmt!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zombie in My Pocket,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.5,NaN,NaN
Zombies!!!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN
Zooloretto,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zooloretto: The Dice Game,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZÈRTZ,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN,...,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
bg_pivot.fillna(0, inplace = True)
bg_pivot

user_name,1 Family Meeple,1000rpm,100pcBlade,1point21gigawatts,2ndPlace,3dicebombers,4Corners,521tiger,5th Beatles,ALGO,...,zaubererer,zautman,zb1035,zedeemia,zefquaavius,zeotter,zgabor,zombiegod,zumba,zumikon
boardgame_name,,,,,,,,,,,,,,,,,,,,,
10 Days in Africa,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10 Days in Asia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10 Days in Europe,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10 Days in the USA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11 nimmt!,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zombie in My Pocket,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.5,0.0,0.0
Zombies!!!,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0
Zooloretto,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zooloretto: The Dice Game,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ZÈRTZ,0.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,...,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:

# folder = "artifacts"
# if not os.path.exists(folder):
#     os.makedirs(folder)
#     print(f" Tạo thành công thư mục {folder} mới.")
# else:
#     os.rmdir(folder)
#     print(f" Xóa thành công thư mục {folder} hiện tại.")
#     os.makedirs(folder)
#     print(f" Tạo thành công thư mục {folder} mới.")

pickle.dump(data, open("artifacts/data_collaborative_filtering_based_RS.pkl", "wb"))

In [7]:
data.to_csv("../Datasets/data_cfb_to_split.csv", index=True)

In [8]:
# split data